import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  buildCatalogImageAudit,
  renderCatalogImageAuditMarkdown,
  type CatalogImageAuditEntry,
} from "@/modules/catalog/application/catalog-image-audit";
import { catalogReadDatasetFromPreview } from "@/modules/catalog/infrastructure/preview-catalog-adapter";
import type { CatalogImageUploadPlan } from "@/modules/imports/catalog/domain/database-apply-types";
import type { CatalogImportPreview } from "@/modules/imports/catalog/domain/types";

const rootDir = process.cwd();
const previewPath = path.join(rootDir, "imports", "generated", "catalog-import-preview.json");
const imagePlanPath = path.join(rootDir, "imports", "generated", "catalog-image-upload-plan.json");
const jsonReportPath = path.join(rootDir, "public", "generated", "catalog-review", "catalog-image-audit.json");
const markdownDocPath = path.join(rootDir, "docs", "CATALOG_IMAGE_AUDIT.md");
const contactSheetPath = path.join(rootDir, "public", "generated", "catalog-review", "catalog-first-page-contact-sheet.html");
const CONTACT_SHEET_SIZE = 48;

async function readJsonFile<T>(filePath: string): Promise<T> {
  const raw = await readFile(filePath, "utf8");
  return JSON.parse(raw) as T;
}

async function readOptionalJsonFile<T>(filePath: string): Promise<T | null> {
  try {
    return await readJsonFile<T>(filePath);
  } catch (error) {
    if (error instanceof Error && "code" in error && (error as NodeJS.ErrnoException).code === "ENOENT") {
      return null;
    }

    throw error;
  }
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function contactSheetCard(entry: CatalogImageAuditEntry, imageSrc: string | null): string {
  const image = entry.selectedPrimary;
  const imgTag =
    image.kind === "none" || !imageSrc
      ? `<div class="ph">Нет изображения</div>`
      : `<img src="${escapeHtml(imageSrc)}" alt="${escapeHtml(image.alt)}" loading="lazy" onload="this.closest('.card').querySelector('.dims').textContent = this.naturalWidth + '×' + this.naturalHeight" />`;

  return `
  <figure class="card">
    <div class="media">${imgTag}</div>
    <figcaption>
      <div class="ref">${escapeHtml(entry.brandName)} — ${escapeHtml(entry.referenceDisplay)}</div>
      <div class="meta">dimensions: <span class="dims">unknown</span></div>
      <div class="meta">source: ${escapeHtml(image.kind)}</div>
      <div class="meta">gallery: ${entry.galleryCount} image(s)</div>
      <div class="meta issue-${escapeHtml(entry.issue)}">issue: ${escapeHtml(entry.issue)}</div>
      <div class="decision">${escapeHtml(entry.decision)}</div>
    </figcaption>
  </figure>`;
}

function renderContactSheetHtml(entries: CatalogImageAuditEntry[], imageSrcs: Array<string | null>): string {
  const cards = entries.map((entry, index) => contactSheetCard(entry, imageSrcs[index] ?? null)).join("\n");

  return `<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8" />
<title>Catalog first-page contact sheet (dev review only)</title>
<style>
  body { margin: 0; padding: 24px; background: #f5f3ee; color: #10161a; font: 13px/1.4 system-ui, sans-serif; }
  h1 { font-size: 18px; margin: 0 0 4px; }
  p.note { color: #747b7f; margin: 0 0 20px; max-width: 70ch; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 16px; }
  .card { margin: 0; border: 1px solid rgba(16,22,26,0.15); background: #fbfaf7; }
  .media { aspect-ratio: 1/1; display: flex; align-items: center; justify-content: center; background: #f0f2f1; overflow: hidden; }
  .media img { max-width: 90%; max-height: 90%; object-fit: contain; }
  .ph { color: #83949d; font-size: 11px; }
  figcaption { padding: 8px 10px 10px; display: grid; gap: 2px; }
  .ref { font-weight: 700; font-size: 12px; }
  .meta { color: #747b7f; font-size: 11px; }
  .issue-no_image, .issue-only_technical_angle_available { color: #b9833d; font-weight: 700; }
  .issue-primary_reselected_from_gallery { color: #315e74; font-weight: 700; }
  .decision { margin-top: 4px; color: #2b3338; font-size: 11px; }
</style>
</head>
<body>
  <h1>Catalog first-page contact sheet (dev review only)</h1>
  <p class="note">
    Generated by src/modules/catalog/cli/catalog-image-audit.ts. Not linked from any production page.
    Open this file through the running dev server (e.g. http://localhost:3001/generated/catalog-review/catalog-first-page-contact-sheet.html)
    so development_zip image sources resolve through the dev-only image resolver.
    This is a static HTML contact sheet, not a flattened JPEG — no image-processing dependency
    (sharp/canvas/jimp) was added to this project to produce a rasterized montage; see
    docs/CATALOG_IMAGE_AUDIT.md for why.
  </p>
  <div class="grid">
    ${cards}
  </div>
</body>
</html>
`;
}

async function main() {
  const preview = await readJsonFile<CatalogImportPreview>(previewPath);
  const imagePlan = await readOptionalJsonFile<CatalogImageUploadPlan>(imagePlanPath);
  const dataset = catalogReadDatasetFromPreview({ preview, imagePlan });
  const report = buildCatalogImageAudit(dataset);
  const markdown = renderCatalogImageAuditMarkdown(report);

  const contactSheetEntries = report.entries.slice(0, CONTACT_SHEET_SIZE);
  const contactSheetImageSrcs = dataset.watches.slice(0, CONTACT_SHEET_SIZE).map((watch) => {
    const image = watch.primaryImage;
    return image.kind === "none" ? null : image.src;
  });
  const contactSheetHtml = renderContactSheetHtml(contactSheetEntries, contactSheetImageSrcs);

  await mkdir(path.dirname(jsonReportPath), { recursive: true });
  await writeFile(jsonReportPath, JSON.stringify(report, null, 2), "utf8");
  await writeFile(markdownDocPath, markdown, "utf8");
  await writeFile(contactSheetPath, contactSheetHtml, "utf8");

  console.log(`Catalog image audit JSON written: ${jsonReportPath}`);
  console.log(`Catalog image audit doc written: ${markdownDocPath}`);
  console.log(`Catalog image contact sheet (HTML) written: ${contactSheetPath}`);
  console.log(
    `Totals: ${report.totalWatches} watches, ${report.withNoImage} with no image, ${report.withOnlyTechnicalAngle} with only technical-angle images, ${report.primaryReselectedCount} primary reselections.`,
  );
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : "Unknown catalog image audit error.";
  console.error(`Catalog image audit failed: ${message}`);
  process.exitCode = 1;
});
